line_length:
  warning: 120
  error: 200
  ignores_urls: true
  ignores_comments: true

disabled_rules:
  - vertical_parameter_alignment

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - UnityKit-Example
  - UnityKit-ExampleTests
